-- Source: SDDBD2.md. Generated idempotent migration.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'feed_posts') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.feed_posts'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'feed_post_likes') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.feed_post_likes'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'feed_post_comments') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.feed_post_comments'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'reading_journal_entries') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.reading_journal_entries'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'reading_list_items') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.reading_list_items'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'user_match_cache') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.user_match_cache'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'newsletter_issues') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.newsletter_issues'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'book_content_warning_votes') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.book_content_warning_votes'; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'book_mood_votes') THEN EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.book_mood_votes'; END IF; END $$;
